language: perl
perl:
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
install:
    - cpanm Test::More Pod::Escapes Unicode::Normalize || { cat ~/.cpanm/build.log ; false ; }
script:
    - prove -lv t
